version: '3.8'

services:
  slot-service:
    build: ./slot-service
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  cart-service:
    build: ./cart-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - ./cart-service/.env
    environment:
      - SLOT_SERVICE_URL=http://slot-service:8001

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    env_file:
      - ./cart-service/.env
    ports:
      - "5432:5432"